export const AUTH_USER = 'AUTH_USER';
export const LOGOUT = 'LOGOUT';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const FETCH_PHOTO_FAILED = 'FETCH_PHOTO_FAILED';
export const FETCH_PHOTO_SUCCESS = 'FETCH_PHOTO_SUCCESS';